<?php
/**
 * @file
 * Code for the Site feature.
 */

include_once 'rivers_site.features.inc';


/**
 * Define handler for homepage.
 *
 * Implements hook_menu()
 */
function rivers_site_menu() {

  $items['home'] = array(
    'title' => 'Whitewater NZ',
    'page callback' => 'rivers_site_home',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['error-403'] = array(
    'title' => 'Access denied',
    'page callback' => 'rivers_access_denied',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * During development, direct to appropriate homepage.
 */
function rivers_site_home() {
  return '<!--{rivers homepage}-->'; /* empty page */
}

/* Custom landing page that we can render a login form onto. */
function rivers_access_denied() {
  $output = drupal_get_form('user_login_block');
  $output['#prefix'] = '<p>You must be logged in to access this page.</p>';

  return $output;
}



/**
 * Implements hook_block_info().
 */
function rivers_site_block_info() {

  $blocks['rivers_copyright'] = array(
    'info' => t('Rivers copyright'),
    'cache' => DRUPAL_CACHE_GLOBAL, // change to DRUPAL_CACHE_GLOBAL when done.
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function rivers_site_block_view($delta = '') {
  switch ($delta) {
    case 'rivers_copyright':
      $block['subject'] = '';
      $block['content'] = t('<div id="copyright">&copy;1999-@year_current Whitewater NZ <a href="http://creativecommons.org/licenses/by-sa/3.0/nz/">CC-BY-SA</a> unless otherwise noted. <a href="/terms">Terms of Use</a>. <a href="/privacy">Privacy Policy</a>.</div>
          <div itemscope itemtype="http://schema.org/Organization">
            <span itemprop="name" style="display: none">Whitewater NZ</span>
            <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
              <span itemprop="streetAddress">PO Box 284</span>,
              <span itemprop="addressLocality">Wellington</span>,
              <span itemprop="postalCode">6140</span>
              <span itemprop="addressCountry">New Zealand</span>.
              <a itemprop="email" href="/contact/admin">whitewaternz@rivers.org.nz</a>
            </div>
          </div>', array('@year_current' => date('Y')));
      return $block;
  }
}
