<?php

/**
 * @file rivers_migrate.module
 */

/**
 * Intentionally left empty, see rivers_migrate.migrate.inc
 * for the actual implementation.
 *
 * @link https://drupal.org/node/1006982
 */

/**
 * Common body field fixes.
 */
function rivers_migrate_map_body($value) {
  $value = str_replace('system/files', 'sites/default/files', $value);
  $value = str_replace('http://rivers.org.nz/sites/default/files', 'https://rivers.org.nz/sites/default/files', $value);
  // Fix for hand-crafted image tag.
  $value = str_replace('imagecache/home_slide', 'styles/home_slide', $value);
  $value = str_replace('home_slide/story_highlight', 'home_slide/public/story_highlight', $value);
  // Fix hard-coded URLs
  $value = str_replace('http://rivers.org.nz/event', '/event', $value);

  return $value;
}
