<?php
/**
 * @file
 * Code for the Rivers Forum feature.
 */

include_once 'rivers_forum.features.inc';

/**
 * Define handler for redirect to whitewater.nz
 *
 * Implements hook_menu()
 */
function rivers_forum_menu() {

  $items['forum'] = array(
    'title' => 'Whitewater NZ',
    'page callback' => 'rivers_forum_redirect',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['forums'] = array(
    'title' => 'Whitewater NZ',
    'page callback' => 'rivers_forum_redirect',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * During development, direct to appropriate homepage.
 */
function rivers_forum_redirect() {

  $url = 'https://whitewater.nz/market-place/?from=' . $_GET['q'];
  header('Location: ' . $url, TRUE, 301);

  if (user_access('administer nodes')) {
    drupal_set_message(t('Would be redirecting to @url', array('@url' => $url)), 'warning');
  }
  else {
    // The "Location" header sends a redirect status code to the HTTP daemon. In
    // some cases this can be wrong, so we make sure none of the code below the
    // drupal_goto() call gets executed upon redirection.
    drupal_exit($url);
  }
}


/**
 * Implements hook_block_info().
 */
function rivers_forum_block_info() {

  $blocks['rivers_forum_summary'] = array(
    'info' => t('Forums list and post count'),
    'cache' => DRUPAL_NO_CACHE, // Change to DRUPAL_CACHE_GLOBAL when done.
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function rivers_forum_block_view($delta = '') {
  switch ($delta) {
    case 'rivers_forum_summary':
      $block['subject'] = t('Forums');
      $block['content'] = rivers_forum_list();
      return $block;
  }
}

/**
 * Return array of forum names and post counts.
 * @return string
 */
function rivers_forum_list() {
  return '<p>Forums are now on whitewater.nz/forums</p>';
  /*$forums = forum_forum_load();
  // Assume only single forum tree in operation.
  $forums_list = array();
  if (isset($forums->forums) && count($forums->forums)) {
    foreach ($forums->forums as $tid => $forum) {
      // Show top-level forums, and exclude empty forums.
      if ($forum->depth == 0 && $forum->num_posts > 0) {
        $forums_list[] = t('!forum, @posts posts', array(
          '!forum' => l($forum->name, 'taxonomy/term/' . $tid, array('attributes' => array(
            'title' => 'Last post ' . rivers_forum_last_post($forum->last_post),
          ))),
          '@posts' => number_format($forum->num_posts),
        ));
      }
    }
  }
  return theme('item_list', array('items' => $forums_list));
  */
}

/**
 * Formats a forum post tooltip, used in links by rivers_forum_list().
 */
function rivers_forum_last_post($post) {
  return t('@time ago by !author', array(
    '@time' => format_interval(time() - $post->created, 1),
    '!author' => theme('username', array(
      'account' => user_load($post->uid),
      'name' => $post->name,
      )),
  ));
}
